<a href="https://colab.research.google.com/github/dave502/course.numpy-pandas/blob/main/homework_02/repeat_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно


In [3]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.


In [4]:
for i in range(2, int(a.size+1)):
  if not a.size % i:
    print('\t') 
    print(np.reshape(a, (i, int(a.size/i)))) 

	
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
	
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
	
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
	
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
	
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [5]:
count = 0
for i in range(2, int(a.size+1)):
  if not a.size % i:
    count += 1
    print('\t') 
    if count < 4:
      print('автоматическое определение количества столбцов')
      print(np.reshape(a, (i, -1)))
    else: 
      print('автоматическое определение количества строк')
      print(np.reshape(a, (-1, int(a.size/i))))

	
автоматическое определение количества столбцов
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
	
автоматическое определение количества столбцов
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
	
автоматическое определение количества столбцов
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
	
автоматическое определение количества строк
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
	
автоматическое определение количества строк
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


4.Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?


In [6]:
# массив, для обращения к элементам которого требуется указать два измерения, является двумерным, следовательно 
# массив, состоящий из одного столбца, является двумерным.

5.Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.


In [7]:
arr = np.random.randn(3, 4)
print (arr)
fl_arr = arr.flatten()
print ("new array fl_arr has size = {} and shape = {}".format(fl_arr.size, fl_arr.shape))

[[ 0.77402969  0.31319444 -0.62842061 -0.17419328]
 [-0.66382285  1.25139809 -0.5824125   0.16293669]
 [ 0.25031601 -0.19592819 -0.47468484  1.9914666 ]]
new array fl_arr has size = 12 and shape = (12,)


6.Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [8]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

7.Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?


In [9]:
b = np.arange(20, 0, -2).reshape(1, 10)
# отличие a от b  в размерности. a - одномерный (вектор), b - двумерный
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

8.Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [10]:
a = np.zeros((2,2))
b = np.ones((3,2))
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

9.Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [11]:
a = np.arange(0, 12)
A = a.reshape(4,3) 
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [54]:
B = np.dot(A, At)
# размер будет 4 х 4 (кол-во строк множимого х кол-во столбцов множителя)
print ("array size for B is {} and shape = {}".format(B.size, B.shape))
B

array size for B is 16 and shape = (4, 4)


array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [55]:
try:
    np.linalg.inv(B) 
except Exception as e:
    print(str(e))  # сингулярная матрица

Singular matrix


10.Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.


In [56]:
np.random.seed(42)

11.Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [57]:
c = np.random.rand(16)
c

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258,
       0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497,
       0.18340451])

12.Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [58]:
C = c.reshape(int(np.sqrt(c.size)), -1)
C # квадратная матрица

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615],
       [0.60111501, 0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497, 0.18340451]])

In [59]:
D = C*10 + B
D

array([[  8.74540119,  23.50714306,  30.31993942,  37.98658484],
       [ 15.5601864 ,  51.5599452 ,  86.58083612, 130.66176146],
       [ 29.01115012,  93.08072578, 149.20584494, 221.69909852],
       [ 40.32442641, 124.12339111, 213.81824967, 303.8340451 ]])

In [60]:
D_inv = np.linalg.inv(D)
print (" определитель матрицы D = {}, \n ранг матрицы D = {}, \n обратная матрица = \n{}". \
       format(np.linalg.det(D),  np.linalg.matrix_rank(D), D_inv))

 определитель матрицы D = -646.0341329026203, 
 ранг матрицы D = 4, 
 обратная матрица = 
[[-12.1682279  -29.82828331  17.10864067   1.86508147]
 [  4.66373225  11.16906589  -6.34968859  -0.75307179]
 [  2.45639627   5.92435938  -3.52400049  -0.28347582]
 [ -2.01894361  -4.77323096   2.80332105   0.2628994 ]]


13.Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [61]:
D_inv[np.where((D_inv<0))] = 0
D_inv[np.where((D_inv>0))] = 1 
D_inv = D_inv.astype(np.int, copy=False)
D_inv # Убедитесь, что в матрице D_inv остались только нули и единицы. 

array([[0, 0, 1, 1],
       [1, 1, 0, 0],
       [1, 1, 0, 0],
       [0, 0, 1, 1]])

In [62]:
E = np.where(D_inv, B, C)
E

array([[3.74540119e-01, 9.50714306e-01, 2.30000000e+01, 3.20000000e+01],
       [1.40000000e+01, 5.00000000e+01, 5.80836122e-02, 8.66176146e-01],
       [2.30000000e+01, 8.60000000e+01, 2.05844943e-02, 9.69909852e-01],
       [8.32442641e-01, 2.12339111e-01, 2.12000000e+02, 3.02000000e+02]])